# Owncloud - CasaOS

# Icono para Owncloud
https://icon.casaos.io/main/all/owncloud.png

# Icono para MariaDB
https://icon.casaos.io/main/all/mariadb.png

# Icono para Redis
https://icon.casaos.io/main/all/redis.png

-------------------------------------------------------- 

version: "3.3"

services: 

  owncloud:
    image: arm32v7/owncloud
    container_name: owncloud-server
    restart: unless-stopped
    ports:
      - 8300:8080
    environment:
      - OWNCLOUD_TRUSTED_DOMAINS=localhost  # 192.168.1.xx | tudominio.com
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mariadb-own
      - OWNCLOUD_ADMIN_USERNAME=user
      - OWNCLOUD_ADMIN_PASSWORD=p4ssw0rd
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis-own    
    volumes:
      - /DATA/AppData/owncloud/files:/mnt/data

--------------------------------------------------------  

version: "3.3"

services: 

  mariadb-own:
    image: yobasystems/alpine-mariadb
    container_name: owncloud-mariadb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
    volumes:
      - /DATA/AppData/owncloud/db:/var/lib/mysql
  
--------------------------------------------------------

version: "3.3"

services: 

  redis-own:
    image: redis:latest
    container_name: owncloud-redis
    restart: unless-stopped
    volumes:
      - /DATA/AppData/owncloud/redis:/data
   
